const CartActionTypes={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    CLEAR_ITEMS_FROM_CART:'CLEAR_ITEMS_FROM_CART',
    REMOVE_ITEMS:'REMOVE_ITEMS',
    CLEAR_CART:'CLEAR_CART'
}

export default CartActionTypes; 